config/routes.rb
Rails.application.routes.draw do
  # get 'dashboards/index' <-- why?
  root 'dashboards#index'

  resources :people
  resources :groups do
    resources :people
  end

  resources :goals
  resources :goalposts
  resources :person_goals, only: [] do
    resources :goalposts, only: [:index]
  end

  resources :users, only: [:new, :create, :show]

  namespace :admin do
    resources :goals, only: [:index]
  end

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/goal.rb
class Goal < ApplicationRecord
  has_many :person_goals
  has_many :people, through: :person_goals

  validates_presence_of :description
end

app/models/goalpost.rb
class Goalpost <ApplicationRecord
  belongs_to :person_goal

  validates_presence_of :date, :person_goal_id, :minutes
end

app/models/group.rb
class Group < ApplicationRecord
  validates_presence_of :title
  has_many :people, dependent: :destroy
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :group
  has_many :person_goals
  has_many :goals, through: :person_goals

  validates_presence_of :name
end

app/models/person_goal.rb
class PersonGoal < ApplicationRecord
  belongs_to :person
  belongs_to :goal
  has_many :goalposts

  validates_presence_of :person_id, :goal_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :person_goals
  has_many :people, through: :person_goals
  has_many :goals, through: :person_goals

  validates_presence_of :password
  validates :username, presence: true, uniqueness: true

  has_secure_password

  enum role: ["default", "admin"]
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end
end

app/controllers/admin/goals_controller.rb
class Admin::GoalsController < Admin::BaseController

  def index
    @goals = Goal.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/goalposts_controller.rb
class GoalpostsController < ApplicationController
  def new
    @goalpost = Goalpost.new
  end

  def create
    @goalpost = Goalpost.new(goalpost_params)
    if @goalpost.save
      flash[:success] = "Goalpost for #{@goalpost.date.strftime('%m/%d/%Y')} created!"
      redirect_to root_path
    else
      render :new
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    @goals = Goal.all
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    if @goal.save
      flash[:success] = "#{@goal.description} Goal created!"
      redirect_to goals_path
    else
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    @goal.update(goal_params)
    if @goal.save
      flash[:success] = "#{@goal.description} Goal updated!"
      redirect_to goals_path
    else
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_path
  end

  private

  def goal_params
    params.require(:goal).permit(:description, :frequency)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      flash[:success] = "#{@group.title} Group created!"
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    @group.update(group_params)
    if @group.save
      flash[:success] = "#{@group.title} Group updated!"
      redirect_to groups_path
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private

  def group_params
    params.require(:group).permit(:title)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
    @groups = Group.all
  end

  def create
    @person = Person.new(person_params)
    @groups = Group.all
    if @person.save
      flash[:success]= "#{@person.name} added!"
      redirect_to people_path
    else
      render :new
    end
  end

  def edit
    @person = Person.find(params[:id])
  end

  def update
    @person = Person.find(params[:id])
    @person.update(person_params)
    if @person.save
      flash[:success] = "#{@person.name} updated!"
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy
    redirect_to people_path
  end

  private

  def person_params
    params.require(:person).permit(:name, :birthday, :group_id, :important_date, :important_date_text)
  end
end

app/controllers/person_goals_controller.rb
class PersonGoalsController < ApplicationController

  def new
    @person_goal = PersonGoal.new
  end

  def create
    @person = Person.find(params[:person_id])
    @goal = Goal.find(params[:goal_id])
    @person_goal = PersonGoal.new(person_goal_params)
    @person_goal[:title] = "#{@person.name}: #{@goal.title}"
    if @person_goal.save
      flash[:success] = "#{@person.name} added to #{@goal.title}!"
      redirect_to goals_path
    else
      render :new
    end
  end

  def person_goal_params
    params.require(:person_goal).permit(:person_id, :goal_id, :title)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    #?
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
  @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/admin/goals/index.html.erb
<div class="title">
  <h2>Admin Goals Index</h2>
</div>

<h4>See Goals for All Users Here</h4>

<% @goals.each do |goal| %>
  <p class=goal_<%= goal.id %>>
    <li>|Goal| <%= goal.description %>
  </li>
<% end %>

app/views/goals/_form.html.erb
<%= form_for @goal do |f| %>

  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :frequency %>
  <%= f.text_field :frequency %>

  <%= f.submit %>

<% end %>

app/views/goals/edit.html.erb
<h2>Edit Goal</h2>
<p> Enter the new title and frequency for this Goal.</p>

<%= render partial: "form" %>

<p>Delete Goal here. Don't worry, this won't delete any People who have this Goal.</p>
<p><%= link_to "Delete Goal", goal_path(@goal), method: "delete" %><p>

app/views/goals/index.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Let's go!</strong> Add your Friendly Goals below!
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

<section class="page">
  <div class="title">
    <h1>My Current Friendly Goals</h1>
  </div>
  <%= link_to "Create New Goal", new_goal_path %>
    <% @goals.each do |goal| %>
      <p class=goal_<%= goal.id %>>
        <h3>Goal: <%= goal.description %></h3>
        <%= link_to "Edit Goal", edit_goal_path(goal) %>
        <p>When: <%= goal.frequency %></p>
        <p>With:</p>
        <% goal.people.each do |person| %>
          <li> <%= link_to person.name, person_path(person) %> </li>
        <% end %>
      </li>
    <% end %>
</section>

<section class="goal collection">
  <table class="table table-dark">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Goal</th>
        <th scope="col">Person</th>
        <th scope="col">Frequency</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th scope="row">1</th>
        <td>Phone call</td>
        <td>Papa</td>
        <td>monthly</td>
      </tr>
      <tr>
        <th scope="row">2</th>
        <td>hang out</td>
        <td>Jennifer</td>
        <td>bi-monthly</td>
      </tr>
      <tr>
        <th scope="row">3</th>
        <td>text</td>
        <td>sister</td>
        <td>every other day</td>
      </tr>
    </tbody>
  </table>
</section>

app/views/goals/new.html.erb
<h2>Create New Goal</h2>
<p> After your Goal is made, click "My People" to add to your Goal.</p>

<%= render partial: "form" %>

app/views/groups/_form.html.erb
<%= form_for @group do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
  
<% end %>

app/views/groups/edit.html.erb
<h2>Edit Group Name</h2>
<p> Enter the new name for this Group.</p>

<%= render partial: "form" %>

<%= link_to "Delete Group and its People", group_path(@group), method: "delete" %>

app/views/groups/index.html.erb
<div class="title">
  <h1>My Groups</h1>
</div>
<%= link_to "Create New Group", new_group_path %>
<h3>To change a person's group, click a person's name below.</h3>

<ul>
  <% @groups.each do |group| %>
    <li class=group_<%= group.id %>>
      <%= group.title %> <%= link_to "Edit Group", edit_group_path(group) %>
      <% group.people.each do |person| %>
        <ul> <%= link_to person.name, edit_group_person_path(group, person) %> </ul>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/groups/new.html.erb
<h2>Create a New Group for your People</h2>
<p> After your Group is made, click "My People" to add to your Group.</p>

<%= render partial: "form" %>

app/views/people/_form.html.erb
<p> Need a new Group for the Person? Click <%= link_to "here", new_group_path %> to create a Group first.</p>

<%= form_for @person do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :group_id %>
  <%= f.collection_select :group_id, Group.all, :id, :title %>


  <%= f.label :birthday %>
  <%= f.date_field :birthday %>
  <%= f.label :important_date_text %>
  <%= f.text_field :important_date_text %>
  <%= f.label :important_date %>
  <%= f.date_field :important_date %>

  <%= f.submit %>

<% end %>

app/views/people/edit.html.erb
<h2><%= "Edit #{@person.name}" %></h2>
<p> Fill in the form below to make changes to this Person.</p>

<%= render partial: "form" %>

<%= link_to "Delete Person", person_path(@person), method: "delete" %>

app/views/people/index.html.erb
<div class="title">
  <h1>My People</h1>
</div>
<%= link_to "Add New Person", new_person_path %>

<h4>Click a Person to see your Goals for them</h4>

<ul>
  <% @people.sort.each do |person| %>
    <li class=person_<%= person.id %>>
      <%= link_to person.name, person_path(person) %>
      <%= person.group.title %>
      <%= link_to "Edit Person", edit_person_path(person) %>
    </li>
  <% end %>
</ul>

app/views/people/new.html.erb
<h2>Add a New Person</h2>
<p> Fill out the form below to add a new Person!</p>
<p> Your Person must start with a Name and a Group. You can add important dates later if you're not sure right now.</p>

<%= render partial: "form" %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>

<ul>
  <li><%= "Group: #{@person.group.title}" %></li>
  <% if @person.birthday %>
    <li><%= "Birthday: #{@person.birthday.strftime('%m/%d/%Y')}" %></li>
  <% end %>
</ul>

<p><%= link_to "<< Back to My People", people_path %>